module.exports = {
    NPC: [
        'Elon Muska (broke version)',
        'Rich Kid who flexes with his dad’s black card',
        'Older Woman in a Luxury Car (she’s judging you)',
        'Owner of the Discord Server',
        'Kimori\'s Kaechan',
        'Your Mom (disappointed)',
        'Your Dad (about to give life advice)',
        'Your Ex who owes you money',
        'Grandma with gambling addiction',
        'meh23_.',
        'Ghost living under your bed',
        'Santaa Claus (he saw your search history)',
        'Yourself from 3 years ago',
        'Your Ancestor who’s ashamed of you',
        'Your Dog (he has more money than you)',
        'Triple T',
        'Skeleton in the closet',
        'Your House (it’s also broke)',
        'Mr. Aintsir',
        'The Archive in Blue\'s Student',
        'UwU Supreme Overlord',
        'Damn Meme',
        'Lyno',
        'Something Sent From Heaven (but broke)',
        'Literally No One Cares But Money Suddenly Drops',
        'Must Be Wind',
        'Holy Cow',
        'Religious Sect That Doesn’t Believe Earth Exists',
        'Alien Here For Your Data',
        'Emperor of Humanity (mid af)',
        'Chat aint GPT',
        'Super AI from 2035 (still unemployed)',
        'Dinosaurus',
        'Niissan',
        'Brazil Guy',
        'Hacker (uses Windows 7)',
        'Corrupt Politician',
        'Scammer from WhatsApp',
        'Street Musician (plays only Wonderwall)',
        'Lost Tourist',
    ],

    // Beg command
    // Beg command - MAXIMUM SOUL
    BegSuccess: [
        'You begged in the toilet and suddenly MrBeast liked your comment',
        'No one came but then a crypto whale randomly dropped 0.5 ETH on you',
        'You went to the bank looking homeless and they just gave you money out of pity',
        'Got hit while begging but a sugar mommy appeared saying "aww poor baby"',
        'Sat outside Gucci looking dead inside and someone Venmo’d you $420',
        'Went live begging and xQC raided you with 500 gifted subs',
        'Broke af so you hit up school and Kimori\'s Kaechan felt bad',
        'You asked your mom and she actually opened her wallet (rare event)',
        'Found a lost iPhone wallet case with Apple Pay still logged in',
        'A mysterious stranger said "you remind me of me in 2009" and gave you $1000',
    ],
    BegFail: [
        'Police arrested you for begging in the women’s toilet again',
        'Your mom wasn’t home (classic)',
        'Livestream begging got 2 views and 1 hate comment',
        'Dad slapped you with the "get a job" speech',
        'Gym bro only gave you "touch grass and lift" advice',
        'Stood in rain for 2 hours and got nothing but pneumonia + L',
        'Your ancestor appeared and said "skill issue" before vanishing',
        'Brazil guy said "ye" and kept walking',
        'Luxury car lady saw you and floored it',
        'You tried to text your gf then remembered you’re single',
        'Join beggar company lil bro',
        'Imagine being this poor lol 😂😂😂',
        'I TOLD U NO',
        'I CANT STOP I CANT STOP I CANT STOP',
        'Ratio + touch grass + L + no maidens',
    ],
    BegStolen: [
        'Random old woman on bike snatched your bag like a pro',
        'Beggar company guy stole everything while screaming "I CANT STOP"',
        'Bike kid did a drive-by theft',
        'You tripped and a kid kicked your money into the drain',
        'Monkey from the market stole your wallet mid-beg',
        'Officer you begged arrested you for "suspicious behavior"',
        'School bully suplexed you and took everything',
        'Your situationship appeared and said "babe send money"',
        'Lost the 1v1 against hydrogen bomb vs coughing baby',
        'Kimori\'s Kaechan walked past like you were invisible',
        'Tried robbing a skeleton… he had no pockets',
        'Brazil guy casually yoinked half your money',
        'Discord owner used /admin deletebalance on you',
    ],

    // Steal command
    StealSuccess: [
        'You pulled the smoothest wallet heist since Ocean’s Eleven',
        'They were watching Skibidi Toilet. You watched their wallet vanish',
        '"LOOK A SHOOTING STAR" — wallet + phone gone',
        'Swapped their wallet with a fake one. They still haven’t noticed',
        'Food court sleight of hand = new PS5 fund',
        'Hugged them goodbye and left with their entire salary',
        'Pointed at something shiny and executed perfect pickpocket',
    ],
    StealFail: [
        'Wrong pocket. They gave you the "bro what are you doing" stare',
        'Your hand shook. You just did the default dance and left',
        'They turned around mid-grab. You said "Zsteal is mid" and walked away',
        'Fumbled and gave them a high five instead. Legendary fail',
        'They had AirPods but 360 awareness. Caught you instantly',
        'Your "casual" walk looked like you were constipated. Super sus',
        'Knocked over an entire shelf. Main character energy (negative)',
    ],
    StealBusted: [
        'Caught red-handed. Whole server spamming L + ratio',
        'Tripped while running and spilled your own wallet. Pain',
        'They had a bodycam. You’re now a Discord meme',
        'Off-duty cop was standing right there. Instant jail arc',
        'Lost money + dignity in one go. Tragic.',
        'They grabbed your wrist and said "nice try kid"',
        'They reverse pickpocketed YOU. Ultimate ratio',
    ],

    // Crime command (Rob)
    CrimeSuccess: [
        'You robbed a bank like it was GTA and actually escaped',
        'Old lady dropped wallet. You pulled a Sonic speedrun.',
        'Snuck into tech store and walked out with 3 gaming PCs',
        'Hacked emptyY database and sold it to the highest bidder',
        'Pickpocketed a rich tourist and found $5000 cash',
        'Hotwired a Lamborghini and sold it in under 20 minutes',
        'Perfect mall heist. Security guards were asleep.',
        'Phishing scam worked. Some boomer sent you his retirement fund.',
    ],
    CrimeFail: [
        'Bank teller laughed at your toy gun. You ran away crying',
        'Old lady folded you like a cheap chair. Hospital bill + L',
        'PC too heavy. Dropped it, broke the glass, ran empty handed',
        'Forgot VPN. Cyber police traced you in 4 seconds.',
        'Pickpocketed an undercover cop. Handcuffs speedrun any%.',
        'Car alarm went nuclear. Whole city woke up',
        'Scam victim reversed it and drained your account.',
    ],
    CrimeWorse: [
        'SWAT team appeared. You’re now someone’s prison wife',
        'Old lady was ex-MMA. You woke up with $50k medical bill',
        'Store owner had shotgun. You got shot + arrested + sued',
        'FBI raided your house at 3AM. Setup = gone',
        'Undercover cop moment. Welcome to jail',
        'Crashed stolen car into police station. Record charges',
        'Victim doxxed you and leaked your browser history',
    ],

    // Job command
    JobStart: [
        'Alarm goes off. You drag your dead soul to the wage cage',
        'Coffee + existential dread = another corporate day',
        'Showed up 15 minutes late with boba like you own the company',
        'Boss said "start working" and your 2 brain cells panicked',
        'Another day of pretending to look busy',
    ],
    JobSuccess: [
        'Never gonna give you up… paycheck just hit different',
        'You actually cooked today. Boss almost smiled.',
        'Grind paid off. Pockets no longer sobbin.',
        'Went full gigachad mode and made it look easy',
        'Finished early. Coworkers gave slow clap + respect',
        'Boss said "good job" — you almost shed a tear',
    ],
    JobFail: [
        'Go work at scam company, you are NOT built for this',
        'Boss gave you the disappointed dad stare',
        'Complete disaster. Even your chair is judging you.',
        'Came late. Boss is now your final boss.',
        'Client asked for your manager. Manager cried',
        'You tried your best… your best was tragic.',
        'Task so hard even Superman said "nah"',
    ],

    // Minigames
    HelperNPC_intro: [
        'Random NPC appears: "Hey bro… can you help me or I’ll haunt your wallet?"',
        'Tiny NPC tugs your shirt: "Psst. I need a favor."',
        'Suspicious NPC waves: "Help me before this gets weird."',
        'Your gf’s dad appears: "Help me or no dating my daughter."',
        'Famous footballer NPC appears: "Help me win the championship!"',
        'Ghost in haunted mansion: "Help or be cursed forever."',
        'Alien NPC: "Fix my spaceship or we both stranded."',
    ],
    HelperNPC_help_success: [
        'NPC cried happy tears and gave you a fat reward',
        'You helped and they blessed your bloodline',
        '"You\'re the best!" — NPC skipped away happily',
        'its was so meh',
        'They give you a box but you refuse to get it'
    ],
    HelperNPC_watch_success: [
        'You watched like a true sigma. Situation fixed itself.',
        'Sometimes doing nothing is the best move. NPC respected it.',
    ],
    HelperNPC_run_fail: [
        'You ran. NPC was faster and angrier.',
        'Running made it worse. Karma caught you instantly.',
    ],
    HelperNPC_fail: [
        'NPC stared at you, sighed, and left disappointed',
        'You were so mid the NPC forgot you existed',
    ],

    GuessNum_intro: [
        'Final boss challenges you to guess a number 1-10 to save the princess',
        'Beggar company boss: "Guess right or stay broke"',
        'Coin Walls, CEO of Bighard, challenges you for the jackpot',
        'Death himself: "Guess right or stay dead"',
        'Your gf’s dad: "Guess right or no daughter"',
    ],
    GuessNum_won: [
        'BULLSEYE. You’re actually him.',
        'You read the universe’s mind. Reward secured.',
        'Destiny chose you today. Bag secured.',
    ],
    GuessNum_lost: [
        'So close yet so broke',
        'Universe said "skill issue"',
        'The number laughed at you and left',
    ],

    PenaltyKick_goal: [
        'TOP BINS!!! Keeper had no chance',
        'GOAAAAL!!! Crowd goes feral',
        'The ball had no choice but to go in',
    ],
    PenaltyKick_saved: [
        'Keeper read your mind like a book',
        'Spectacular save. You got ratio’d by the keeper.',
    ],

    // Leaderboard
    LeaderboardConfig: {
        DefaultCategory: 'money',
        PageSize: 5,
        Color: {
            Gold: '#ffd700',
            DeepGreen: '#215004',
            BloodRed: '#931313',
            DirtyGold: '#93900e',
            DeepBlue: '#403d98',
            DeepPurple: '#3e0e5e',
            Magenta: '#ea5299',
            Orange: '#e67729',
            MustardYellow: '#e6d129',
            Cyan: '#0ea096',
            SkyBlue: '#53a0ea',
        },
        Emoji: {
            '1': '🥇',
            '2': '🥈',
            '3': '🥉',
            '4': '🔹',
            '5': '🔹',
            '6': '🔹',
            '7': '🔹',
            '8': '🔸',
            '9': '🔸',
            '10': '🔸',
        }
    }
}